image: docker:19
services:
  - docker:19-dind

cache:
  paths:
    - ./.m2/repository
    # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

stages:
  - package
  - build
  - deploy

package:
  image: maven:3.8.5-jdk-11
  stage: package
  script:
    - mvn -T20 clean install
  artifacts:
    when: always
    paths:
      - modules/clb-api/target/*.jar
    expire_in: 1 week
  only:
    - main

build:
  stage: build
  script:
    - docker logout
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --no-cache -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
    - release

deploy:
  image:
    name: kiwigrid/gcloud-kubectl-helm
  stage: deploy
  script:
    - echo $GCLOUD_SERVICE_KEY |  base64 -d > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
    - gcloud projects list
#    - gcloud config set project cloudbet-381210
#    - gcloud config set container/cluster clb-cluster
#    - gcloud config set compute/zone australia-southeast2-a
#    - kubectl config set-context --current --namespace=default
#    - cd charts/clb-charts
#    - helm upgrade --install clb-be -n default .
#    - kubectl rollout restart deployment clb-be
  only:
    - main
    - release
