image: docker:19
services:
  - docker:19-dind

cache:
  paths:
    - ./.m2/repository
    # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

stages:
  - package
  - build
  - deploy

package:
  image: maven:3.8.5-jdk-11
  stage: package
  script:
    - mvn -T20 clean install
  artifacts:
    when: always
    paths:
      - modules/clb-api/target/*.jar
    expire_in: 1 week
  only:
    - main
    - cicd

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
