app:
  cors:
    allow-origins: ${cors.allow-origins:http://localhost:4200}
  url-crawl: https://www.ladbrokes.com.au
reactor:
  parallel:
    default-threads: 20
server:
  jetty:
    threads:
      max: 50
  port: ${app.port:20001}
logging:
  file:
    name: ./logs/cloudbet.log
  level:
    root: ${log.level.root:info}
    org:
      springframework: ${log.level.spring:info}
    com:
      tvf:
        cloudbet: ${log.level.app:debug}
  pattern:
    console: "%d{ISO8601} %highlight(%-5level) [%blue(%t)] [%blue(%X{remoteAddr})] [%cyan(%X{tenant})] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %p %C{1.} [%t] [%X{remoteAddr}] [%X{tenant}] %m%n"
spring:
  redis:
    host: ${redis.host:34.129.76.56}
    port: ${redis.port:6379}
    password: ${redis.password:password123}
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
#  webflux:
#    base-path: /cloudbet/api
  r2dbc:
    url: ${postgresql.datasource.dbUrl:r2dbc:postgresql://104.199.244.66:5432/cloudbet_2023_03_16}
    pool:
      enabled: true
      max-size: 5
      max-life-time: 60000 # 10 minutes allowed for connection life time
      initial-size: 5
      max-idle-time: 5000
    username: ${postgresql.datasource.username:postgres}
    password: ${postgresql.datasource.password:admin123}
    properties:
      schema: clb_db
  flyway:
    out-of-order: true
    schemas:
      - ${postgresql.schema:clb_db}
    url: ${postgresql.datasource.flywayUrl:jdbc:postgresql://104.199.244.66:5432/cloudbet_2023_03_16}
    user: ${postgresql.datasource.username:postgres}
    password: ${postgresql.datasource.password:admin123}
socket-server:
  host: ${socket.host:localhost}
  port: 20002
