app:
  cors:
    allow-origins: ${cors.allow-origins:http://localhost:4200}
  url-crawl: https://www.ladbrokes.com.au
reactor:
  parallel:
    default-threads: 20
server:
  jetty:
    threads:
      max: 50
  port: ${app.port:20001}
logging:
  file:
    name: ./logs/cloudbet.log
  level:
    root: ${log.level.root:info}
    org:
      springframework: ${log.level.spring:info}
    com:
      tvf:
        cloudbet: ${log.level.app:debug}
  pattern:
    console: "%d{ISO8601} %highlight(%-5level) [%blue(%t)] [%blue(%X{remoteAddr})] [%cyan(%X{tenant})] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %p %C{1.} [%t] [%X{remoteAddr}] [%X{tenant}] %m%n"
spring:
  redis:
    host: 34.129.76.56
    port: 6379
    password: password123
  main:
    allow-bean-definition-overriding: true
  webflux:
    base-path: /cloudbet/api
  r2dbc:
    url: ${postgresql.datasource.dbUrl:r2dbc:postgresql://104.199.244.66:5432/cloudbet_2023_03_16}
    pool:
      enabled: true
      max-size: 5
      max-life-time: 60000 # 10 minutes allowed for connection life time
      initial-size: 5
      max-idle-time: 5000
    username: ${postgresql.datasource.username:postgres}
    password: ${postgresql.datasource.password:admin123}
    properties:
      schema: clb_db
  flyway:
    out-of-order: true
    schemas:
      - ${postgresql.schema:clb_db}
    url: ${postgresql.datasource.dbUrl:jdbc:postgresql://104.199.244.66:5432/cloudbet_2023_03_16}
    user: ${postgresql.datasource.username:postgres}
    password: ${postgresql.datasource.password:admin123}
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      minimum-idle: 2 # 3 min-connection allowed in pool
      maximum-pool-size: 5 # 6 max-connection allowed in pool
      idle-timeout: 5000 # 2 minutes allowed for connection idle
      keepalive-time: 60000 # each 5 minutes to re-"pinged" the connection
      max-lifetime: 600000 # 10 minutes allowed for connection life time
      leak-detection-threshold: 5000 # only 5 seconds allowed connection can be out of the pool
    password: ${postgresql.datasource.password:admin123}
    driver-class-name: org.postgresql.Driver
    username: ${postgresql.datasource.username:clb_db}
    url: ${postgresql.datasource.dbUrl:jdbc:postgresql://104.199.244.66:5432/cloudbet_2023_03_16}
socket-server:
  host: localhost
  port: 20002
