app:
  cors:
    allow-origins: ${cors.allow-origins:http://localhost:8082}
  url-crawl: https://www.ladbrokes.com.au
reactor:
  netty:
    ioWorkerCount: 50
server:
  port: ${app.port:20001}
logging:
  pattern:
    console: "%d{ISO8601} %highlight(%-5level) [%blue(%t)] [%blue(%X{remoteAddr})] [%cyan(%X{tenant})] %yellow(%C{1.}): %msg%n%throwable"
spring:
  redis:
    host: ${redis.host:34.129.203.3}
    port: ${redis.port:6379}
    password: ${redis.password:password123}
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  webflux:
    base-path: ${base.path:/cloudbet/api}
  r2dbc:
    url: ${postgresql.datasource.dbUrl:r2dbc:postgresql://34.129.10.71:5432/clb_db}
    pool:
      enabled: true
      max-size: 5
      max-life-time: 60000 # 10 minutes allowed for connection life time
      initial-size: 5
      max-idle-time: 5000
    username: ${postgresql.datasource.username:postgres}
    password: ${postgresql.datasource.password:admin123}
    properties:
      schema: clb_db
  flyway:
    out-of-order: true
    schemas:
      - ${postgresql.schema:clb_db}
    url: ${postgresql.datasource.flywayUrl:jdbc:postgresql://34.129.10.71:5432/clb_db}
    user: ${postgresql.datasource.username:postgres}
    password: ${postgresql.datasource.password:admin123}
socket-server:
  host: ${socket.host:34.129.159.192}
  port: 20002
