app:
  cors:
    allow-origins: ${cors.allow-origins:http://localhost:4200}
  url-crawl: https://www.ladbrokes.com.au
server:
  jetty:
    threads:
      max: 50
  port: ${app.port:20001}
logging:
  file:
    name: ./logs/cloudbet.log
  level:
    root: ${log.level.root:info}
    org:
      springframework: ${log.level.spring:info}
    com:
      tvf:
        cloudbet: ${log.level.app:debug}
  pattern:
    console: "%d{ISO8601} %highlight(%-5level) [%blue(%t)] [%blue(%X{remoteAddr})] [%cyan(%X{tenant})] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %p %C{1.} [%t] [%X{remoteAddr}] [%X{tenant}] %m%n"
spring:
  webflux:
    base-path: /cloudbet/api